### ISSUE TITLE
can not rollback migrations

### ISSUE THREAD

**Issue by oscnet** [ckuttruff/clj-sql-up#12] opened 2015-03-20 04:48 UTC
lein clj-sql-up rollback 10
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
 at clojure.lang.RT.longCast (RT.java:1151)
 clj_sql_up.migrate$rollback.invoke (migrate.clj:59)

**Comment by ckuttruff** [comment] 2015-03-20 05:08
@oscnet sorry you ran into an issue; what version are you running?  will try to reproduce right now so we can get this fixed asap

**Comment by ckuttruff** [comment] 2015-03-20 05:13
yup, just reproduced with latest version.
Looking into it now

**Comment by ckuttruff** [comment] 2015-03-20 05:27
tracked it down.

`(.Long "3")` coerces the string into a number, but `(long "3")` does not.

This was changed in this PR: https://github.com/ckuttruff/clj-sql-up/pull/7
but the issue didn't come up then.  fix coming

**Comment by ckuttruff** [comment] 2015-03-20 05:41
Okay, just pushed version 0.3.6 to clojars which fixes this problem.

Please let me know if you have any other issues.
Thanks so much for reporting the problem!

**Comment by ckuttruff** [comment] 2015-03-20 05:45
closing since this should be resolved (just tested)

Please reopen / let me know if you have any problems

**Closed by ckuttruff** 2015-03-20 05:45 UTC

**Comment by oscnet** [comment] 2015-03-20 11:30
nice!thanks.

**Comment by ckuttruff** [comment] 2015-03-31 06:03
Oh, noticed I hadn't linked to the relevant commit.
Here it is:
https://github.com/ckuttruff/clj-sql-up/commit/add95edc1287504d549a62b6ad77da4df480bde9
